### ISSUE TITLE
dvtm support?

### ISSUE THREAD

**Issue by travankor** [nmeum/insomnia#1]
Just wondering, can insomnia use[ dvtm](http://www.brain-dump.org/projects/dvtm/) instead of depending on tmux?

**Comment by nmeum** [comment]
Well…technically that would certainly be possible, would mostly require modifications to the `insomnia.in` file. However, I personally use tmux instead of dvtm (since the former ships with OpenBSD by default) and usually don't add features that I don't use myself. If you want to use dvtm you need to maintain your own fork, sorry.
